namespace UOInterface
{
    public enum SkillLock : byte
    {
        Up = 0,
        Down = 1,
        Locked = 2
    }

    public enum Skill : ushort
    {
        Alchemy,
        Anatomy,
        AnimalLore,
        ItemID,
        ArmsLore,
        Parry,
        Begging,
        Blacksmith,
        Fletching,
        Peacemaking,
        Camping,
        Carpentry,
        Cartography,
        Cooking,
        DetectHidden,
        Discordance,
        EvalInt,
        Healing,
        Fishing,
        Forensics,
        Herding,
        Hiding,
        Provocation,
        Inscribe,
        Lockpicking,
        Magery,
        MagicResist,
        Tactics,
        Snooping,
        Musicianship,
        Poisoning,
        Archery,
        SpiritSpeak,
        Stealing,
        Tailoring,
        AnimalTaming,
        TasteID,
        Tinkering,
        Tracking,
        Veterinary,
        Swords,
        Macing,
        Fencing,
        Wrestling,
        Lumberjacking,
        Mining,
        Meditation,
        Stealth,
        RemoveTrap,
        Necromancy,
        Focus,
        Chivalry,
        Bushido,
        Ninjitsu,
        Spellweaving,
        Mysticism,
        Imbuing,
        Throwing
    }
}